extract = 'total_dyn_inst: (\d+)'
benchmarks = 'test/benchmarks/core/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.crude-roundtrip]
pipeline = [
    "bril2json",
    "python to_ssa.py",
    "python from_ssa.py",
    "brili -p {args}",
]

[runs.tdce-roundtrip]
pipeline = [
    "bril2json",
    "python to_ssa.py",
    "python from_ssa.py",
    "python ../l3/tdce.py",
    "brili -p {args}",
]

