# Run with `brench -j 1 brench.toml > brench.out`

extract = 'total_dyn_inst: (\d+)'
benchmarks = 'test/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.speculate]
pipeline = [
    "bril2json",
    "python3 speculate.py --run-brili-ts -p {args}",
    "brili -p {args}",
]
