extract = 'total_dyn_inst: (\d+)'
benchmarks = 'test/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

# Seems like running brench on dynamically changing files cause nondeterministic results in brench.out, 
# even though the benchmarks are correct when testing manually

[runs.speculate]
pipeline = [
    "bril2json",
    "python3 speculate.py --run-brili-ts -p {args}",
    "brili -p {args}",
]
